//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewindVHSDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int movieId { get; set; }
        public Nullable<int> filmYear { get; set; }
        public string filmName { get; set; }
        public Nullable<decimal> filmPrice { get; set; }
        public string filmCast { get; set; }
    }
}
